name: sheriff
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sheriff:
    runs-on: ubuntu-latest

    env:
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ./nodejs/package-lock.json

      - name: install deps nodejs
        working-directory: ./
        run: |
          npm install

      - name: eslint nodejs
        working-directory: ./
        run: npm run-script lint

      - name: runs tests
        working-directory: ./
        run: npm test
